/**
 * Fresh Card Image Mapping System - Authentic Artwork
 * Uses clean folder structure to bypass cache issues
 */

export const authenticCardPaths: { [key: string]: string } = {
  // Major Arcana - Authentic Artwork V2
  "0": "/authentic-cards/major-arcana/authentic-fool-v2.png",
  "1": "/authentic-cards/major-arcana/authentic-magician-v2.png", 
  "2": "/authentic-cards/major-arcana/authentic-high-priestess-v2.png",
  "3": "/authentic-cards/major-arcana/authentic-empress-v2.png",
  "4": "/authentic-cards/major-arcana/authentic-emperor-v2.png",
  
  // Remaining Major Arcana (will be generated)
  "5": "/authentic-cards/major-arcana/05-hierophant.png",
  "6": "/authentic-cards/major-arcana/06-lovers.png",
  "7": "/authentic-cards/major-arcana/07-chariot.png",
  "8": "/authentic-cards/major-arcana/08-strength.png",
  "9": "/authentic-cards/major-arcana/09-hermit.png",
  "10": "/authentic-cards/major-arcana/10-wheel-of-fortune.png",
  "11": "/authentic-cards/major-arcana/11-justice.png",
  "12": "/authentic-cards/major-arcana/12-hanged-man.png",
  "13": "/authentic-cards/major-arcana/13-death.png",
  "14": "/authentic-cards/major-arcana/14-temperance.png",
  "15": "/authentic-cards/major-arcana/15-devil.png",
  "16": "/authentic-cards/major-arcana/16-tower.png",
  "17": "/authentic-cards/major-arcana/17-star.png",
  "18": "/authentic-cards/major-arcana/18-moon.png",
  "19": "/authentic-cards/major-arcana/19-sun.png",
  "20": "/authentic-cards/major-arcana/20-judgement.png",
  "21": "/authentic-cards/major-arcana/21-world.png",
  
  // Minor Arcana - Existing paths (will migrate later)
  "w1": "/assets/cards/ace-of-wands.png",
  "w2": "/assets/cards/two-of-wands.png",
  "w3": "/assets/cards/three-of-wands.png",
  "w4": "/assets/cards/four-of-wands.png",
  "w5": "/assets/cards/five-of-wands.png",
  "w6": "/assets/cards/six-of-wands.png",
  "w7": "/assets/cards/seven-of-wands.png",
  "w8": "/assets/cards/eight-of-wands.png",
  "w9": "/assets/cards/nine-of-wands.png",
  "w10": "/assets/cards/ten-of-wands.png",
  "wp": "/assets/cards/page-of-wands.png",
  "wn": "/assets/cards/knight-of-wands.png",
  "wq": "/assets/cards/queen-of-wands.png",
  "wk": "/assets/cards/king-of-wands.png",
  
  "c1": "/assets/cards/ace-of-cups.png",
  "c2": "/assets/cards/two-of-cups.png",
  "c3": "/assets/cards/three-of-cups.png",
  "c4": "/assets/cards/four-of-cups.png",
  "c5": "/assets/cards/five-of-cups.png",
  "c6": "/assets/cards/six-of-cups.png",
  "c7": "/assets/cards/seven-of-cups.png",
  "c8": "/assets/cards/eight-of-cups.png",
  "c9": "/assets/cards/nine-of-cups.png",
  "c10": "/assets/cards/ten-of-cups.png",
  "cp": "/assets/cards/page-of-cups.png",
  "cn": "/assets/cards/knight-of-cups.png",
  "cq": "/assets/cards/queen-of-cups.png",
  "ck": "/assets/cards/king-of-cups.png",
  
  "s1": "/assets/cards/ace-of-swords.png",
  "s2": "/assets/cards/two-of-swords.png",
  "s3": "/assets/cards/three-of-swords.png",
  "s4": "/assets/cards/four-of-swords.png",
  "s5": "/assets/cards/five-of-swords.png",
  "s6": "/assets/cards/six-of-swords.png",
  "s7": "/assets/cards/seven-of-swords.png",
  "s8": "/assets/cards/eight-of-swords.png",
  "s9": "/assets/cards/nine-of-swords.png",
  "s10": "/assets/cards/ten-of-swords.png",
  "sp": "/assets/cards/page-of-swords.png",
  "sn": "/assets/cards/knight-of-swords.png",
  "sq": "/assets/cards/queen-of-swords.png",
  "sk": "/assets/cards/king-of-swords.png",
  
  "p1": "/assets/cards/ace-of-pentacles.png",
  "p2": "/assets/cards/two-of-pentacles.png",
  "p3": "/assets/cards/three-of-pentacles.png",
  "p4": "/assets/cards/four-of-pentacles.png",
  "p5": "/assets/cards/five-of-pentacles.png",
  "p6": "/assets/cards/six-of-pentacles.png",
  "p7": "/assets/cards/seven-of-pentacles.png",
  "p8": "/assets/cards/eight-of-pentacles.png",
  "p9": "/assets/cards/nine-of-pentacles.png",
  "p10": "/assets/cards/ten-of-pentacles.png",
  "pp": "/assets/cards/page-of-pentacles.png",
  "pn": "/assets/cards/knight-of-pentacles.png",
  "pq": "/assets/cards/queen-of-pentacles.png",
  "pk": "/assets/cards/king-of-pentacles.png"
};